#!/bin/sh

### BEGIN INIT INFO
# Provides:          usbModem
# Should-Stop:
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: usbModem
# Description:
### END INIT INFO

set -e

# Include core init functions if needed


case "${1:-}" in
  stop)
        echo "* Stopping USB Modems "
        kill `cat /var/run/usbModem1.pid`
        kill `cat /var/run/usbModem2.pid`
        ;;

  start)
        echo "* Starting USB Modems "
        /usr/local/bin/usbModem.sh
        ;;

  *)
        echo "Usage: ${0:-} {start|stop|status|}" >&2
        exit 1
        ;;
esac
